#!/usr/bin/env python
import os
import argparse
import subprocess
import sys

parser = argparse.ArgumentParser(description='Test runner')
parser.add_argument('test', nargs='*', type=str, 
                   help='the path to the matlab test to execute')
parser.add_argument('--exclude', nargs='+', type=str, 
                   help='the path to the matlab test to exclude')
args, unknown = parser.parse_known_args()

print args

def line_prepender(filename, line):
    with open(filename, 'r+') as f:
        content = f.read()
        f.seek(0, 0)
        f.write(line.rstrip('\r\n') + '\n' + content)

if len(args.test) == 0:
    tests = os.listdir('tests')
else:
    tests = [os.path.basename(t) for t in args.test]

runnable = []

for t in tests:
    print 'Compiling ' + os.path.join('tests', t)
    f = os.path.basename(t)
    func = os.path.splitext(f)[0]
    outfile = os.path.join('builds', func + '.js')
    cmd = ['compilers/matjuice-v1.1.0/matjuice', os.path.join('tests', t), outfile, 'DOUBLE&1*1&REAL']
    output = subprocess.check_output(cmd)
    line_prepender(outfile, "var tap = require('tap');\n")
    with open(outfile, "a") as myfile:
        myfile.write("\n" + func + "();\n tap.pass();\n")
    runnable.append(outfile)

